name: appSp16Cloud
tags:
  app: appSp16Cloud

domain:
  hostedzone_id: XXXXXXXXXX
  hostedzone_name: XXXXXXXXXXXXXX.XXX
  cert_arn: cert_arn

network:
  vpc:
    natGatewaySubnetName: Public
    maxAzs: 2
