aws_account: "188775091215"
aws_region: us-east-1

network:
  vpc:
    cidr: 10.0.0.0/21

  subnets:
    private:
      - cidr_block: 10.0.0.0/24
        avl_zone: us-east-1a
      - cidr_block: 10.0.1.0/24
        avl_zone: us-east-1b
    public:
      - cidr_block: 10.0.4.0/25
        avl_zone: us-east-1c
      - cidr_block: 10.0.4.128/25
        avl_zone: us-east-1d


compute:
  ec2:
    instance1:
      name: Instance1
      subnet_name: PublicSubnet1
      ami: ami-0be0e902919675894
      instance_type: m5.xlarge
      keypair: dev
      ebs:
        - 1000
        - 2000
        - 3000
      security_group:
        inbound:
          - 22
          - 3389
          - 443
        outbound:
          - all
      

    instance2:
      name: Instance2
      subnet_name: PublicSubnet2
      ami: ami-0be0e902919675894
      instance_type: m5.xlarge
      keypair: dev
      ebs:
        - 1000
        - 2000
      security_group:
        inbound:
          - 22
          - 3389
          - 443
        outbound:
          - all
      
    instance3:
      name: Instance2
      subnet_name: PrivateSubnet1
      instance_type: m5.xlarge
      ami: ami-04cbc618ff43040aa
      keypair: dev
      ebs:
        - 1000
        - 2000
        - 3000
        - 4000
      security_group:
        inbound:
          - 22
          - 3389
          - 1443
        outbound:
          - all
      